### PR TITLE
Tuning fixes

### PR DESCRIPTION
**Pull request by jamesdbaker**
Some minor changes required to get tuning working on a Ubuntu machine

### CODE REVIEW

**Review by ivan-zapreev — APPROVED** [review]

**Review by ivan-zapreev — CHANGES_REQUESTED** [review]
The lattice file extention are used in the tuning scripts as well so changing it only here will break tuning, so we either need to change these in all places or keep as is.

**Review by ivan-zapreev — CHANGES_REQUESTED** [review]
Should not the error output modification be consistent over all scripts? it was >& and in one script it changed to 2>&1 and in another to just >. Should not it actually be 2>&1 1>[error_file_name] ? And will it also work in the bash shell of CentOS?

**Review by ivan-zapreev — CHANGES_REQUESTED** [review]
The server URL introduction is a great step in a right direction, however, the actual server port is not guaranteed to be 9001 but has a value specified in the server's configuration file. The complete solution would be extracting the server port from the available server config file and using it to connect the client.

**Comment by jamesdbaker** [comment]
RE: The file extension, I did revert this change so I don't think this is now an issue. However, there are inconsistencies in the existing example files so it's not clear what it should be.

For example: https://github.com/ivan-zapreev/Distributed-Translation-Infrastructure/blob/master/cfg/server.cfg and https://github.com/ivan-zapreev/Distributed-Translation-Infrastructure/blob/master/demo/no-tls/configs/server.1.cfg

**Comment by jamesdbaker** [comment]
RE: Other comments, I've made the requested changes but I'm unable to test on CentOS as I only have access to a Ubuntu machine.

**Review by ivan-zapreev — APPROVED** [review]

**Comment by ivan-zapreev** [comment]
Thank you James for the improvements!

**Pull request merged**
